[Interface]
PrivateKey = CHANGE_ME_PRIVATE_KEY
Address = CHANGE_ME_ADDRESS/32
DNS = 10.64.0.1

[Peer]
PublicKey = CHANGE_ME_SERVER_PUBKEY
Endpoint = CHANGE_ME_SERVER_IP:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
